### ISSUE TITLE
分享一个解决安装宋体后QQ字体变宋体问题的解决方法：https://bbs.deepin.org/zh/post/213530?offset=0&postId=1269543

### ISSUE THREAD

**Issue by goat1515** [vufa/deepin-wine-qq-arch#64]

**Comment by vufa** [comment]
感谢帮助，已经添加到 [README](https://github.com/vufa/deepin-wine-qq-arch#%E5%AD%97%E4%BD%93%E5%8F%91%E8%99%9A%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96%E5%AD%97%E4%BD%93)
