### ISSUE TITLE
qq tim 截图是黑的

### ISSUE THREAD

**Issue by day0xy** [vufa/deepin-wine-qq-arch#72]
内核5.16.15-arch1-1
从aur打包安装的

截图是黑屏

**Comment by DearjhonXXX9** [comment]
解决方法是 使用x11 wm ，而不是新版的wayland

**Comment by lejay89** [comment]
> 

用Wayland的话有办法解决截图黑屏问题吗？

**Comment by xc3z** [comment]
没&nbsp; 一直用的x11



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月20日(周一) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vufa/deepin-wine-qq-arch] qq tim 截图是黑的 (Issue #72)




   
用Wayland的话有办法解决截图黑屏问题吗？

**Comment by lejay89** [comment]
> 

这个具体是什么原因知道吗
