### ISSUE TITLE
Manjaro通过yay安装后缺少安全组件，无法启动

### ISSUE THREAD

**Issue by DissolveBoi** [vufa/deepin-wine-qq-arch#75]
通过yay方式安装后无法启动，弹窗报错：
![截图_2022-04-06_10-46-38](https://user-images.githubusercontent.com/71422450/161885826-cb103ce2-df07-4b8a-88d8-e64c02ae396e.png)

**Comment by vufa** [comment]
与 https://github.com/vufa/deepin-wine-qq-arch/issues/71 重复
