### ISSUE TITLE
每次打开都需要重新安装

### ISSUE THREAD

**Issue by askfiy** [vufa/deepin-wine-qq-arch#76]
我的系统是 Manjaro，刚重装了一次系统。

在重装之前它运行的一直很好，但是现在我发现每次打开 QQ 他都需要重新安装一次。

我不知道为什么会这样...

**Comment by vufa** [comment]
安装完试试运行命令：
```bash
cat /opt/apps/com.qq.im.deepin/files/files.md5sum > $HOME/.deepinwine/Deepin-QQ/PACKAGE_VERSION
```

**Comment by askfiy** [comment]
这有效果 ...

**Comment by askfiy** [comment]
啊，但是他会说我已经登录了这个帐号。不能重复登录了，其实我已经关闭了 QQ 了 ..

**Comment by vufa** [comment]
关闭QQ会有残留的QQ进程，现阶段不能解决，可以重启一下系统

**Comment by askfiy** [comment]
> 关闭QQ会有残留的QQ进程，现阶段不能解决，可以重启一下系统

已经重启过了，问题依然存在 ..
